/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Car;

import javax.swing.JFrame;

/**
 *
 * @author tushar
 */
public class WelcomePage extends javax.swing.JFrame {

	/**
	 * Creates new form WelcomePage
	 */
	public WelcomePage() {
		initComponents();
	}
MainLoginWindow login=new MainLoginWindow();

	registration register=new registration();
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                header = new javax.swing.JPanel();
                menu = new javax.swing.JPanel();
                menuicon = new javax.swing.JPanel();
                menuhide = new javax.swing.JPanel();
                button1 = new java.awt.Button();
                button2 = new java.awt.Button();
                dashboard = new javax.swing.JPanel();
                label2 = new java.awt.Label();
                label3 = new java.awt.Label();
                label4 = new java.awt.Label();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                header.setBackground(new java.awt.Color(5, 10, 46));
                header.setPreferredSize(new java.awt.Dimension(800, 50));
                header.setLayout(new java.awt.BorderLayout());
                getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

                menu.setPreferredSize(new java.awt.Dimension(270, 450));
                menu.setLayout(new java.awt.BorderLayout());

                menuicon.setBackground(new java.awt.Color(5, 10, 46));
                menuicon.setPreferredSize(new java.awt.Dimension(50, 450));

                javax.swing.GroupLayout menuiconLayout = new javax.swing.GroupLayout(menuicon);
                menuicon.setLayout(menuiconLayout);
                menuiconLayout.setHorizontalGroup(
                        menuiconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
                );
                menuiconLayout.setVerticalGroup(
                        menuiconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 450, Short.MAX_VALUE)
                );

                menu.add(menuicon, java.awt.BorderLayout.LINE_START);

                menuhide.setBackground(new java.awt.Color(25, 29, 74));
                menuhide.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N

                button1.setBackground(new java.awt.Color(51, 51, 51));
                button1.setFont(new java.awt.Font("DejaVu Serif Condensed", 3, 18)); // NOI18N
                button1.setForeground(new java.awt.Color(255, 255, 255));
                button1.setLabel("REGISTER");
                button1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button1ActionPerformed(evt);
                        }
                });

                button2.setBackground(new java.awt.Color(102, 102, 102));
                button2.setFont(new java.awt.Font("DejaVu Serif Condensed", 3, 18)); // NOI18N
                button2.setForeground(new java.awt.Color(255, 255, 255));
                button2.setLabel("LOGIN");
                button2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
                menuhide.setLayout(menuhideLayout);
                menuhideLayout.setHorizontalGroup(
                        menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuhideLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addContainerGap(39, Short.MAX_VALUE))
                );
                menuhideLayout.setVerticalGroup(
                        menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuhideLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(191, Short.MAX_VALUE))
                );

                menu.add(menuhide, java.awt.BorderLayout.CENTER);

                getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

                dashboard.setBackground(new java.awt.Color(19, 48, 98));
                dashboard.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

                label2.setAlignment(java.awt.Label.CENTER);
                label2.setBackground(new java.awt.Color(0, 0, 0));
                label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                label2.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
                label2.setForeground(new java.awt.Color(255, 255, 255));
                label2.setText("TO");

                label3.setAlignment(java.awt.Label.CENTER);
                label3.setBackground(new java.awt.Color(0, 0, 0));
                label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                label3.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
                label3.setForeground(new java.awt.Color(255, 255, 255));
                label3.setText("WELCOME");

                label4.setAlignment(java.awt.Label.CENTER);
                label4.setBackground(new java.awt.Color(255, 255, 255));
                label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                label4.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 48)); // NOI18N
                label4.setForeground(new java.awt.Color(0, 0, 0));
                label4.setText("MARUTI SUZUKI");

                javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
                dashboard.setLayout(dashboardLayout);
                dashboardLayout.setHorizontalGroup(
                        dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashboardLayout.createSequentialGroup()
                                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dashboardLayout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dashboardLayout.createSequentialGroup()
                                                .addGap(124, 124, 124)
                                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                );
                dashboardLayout.setVerticalGroup(
                        dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashboardLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
                );

                getContentPane().add(dashboard, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
                // TODO add your handling code here
register.setVisible(true);
register.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);








	
        }//GEN-LAST:event_button1ActionPerformed

        private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
     login.setVisible(true);
login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		// TODO add your handling code here:
        }//GEN-LAST:event_button2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WelcomePage().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Button button1;
        private java.awt.Button button2;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JPanel dashboard;
        private javax.swing.JPanel header;
        private java.awt.Label label2;
        private java.awt.Label label3;
        private java.awt.Label label4;
        private javax.swing.JPanel menu;
        private javax.swing.JPanel menuhide;
        private javax.swing.JPanel menuicon;
        // End of variables declaration//GEN-END:variables

	private void Error() {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}
}
